apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${repo}
  labels:
    app.kubernetes.io/name: load-balancer-${repo}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-${repo}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-${repo}
    spec:
      containers:
      - name: ${repo}
        image: ${image}
        env: ${env}
        ports:
        - containerPort: ${containerPort}
