apiVersion: v1
kind: Service
metadata:
  name: ${repo}-service
  labels:
    app.kubernetes.io/name: load-balancer-${repo}
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: ${targetPort}
    protocol: TCP
  selector:
    app.kubernetes.io/name: load-balancer-${repo}
